"""Auto-generated CAD part 'cam_lock' (shape=camlock) for usermanualXR.

Generated by spatail_cad_templates.py - edit the build-plan `cad` block or
supply a bespoke generator instead of hand-editing this file.
Units: millimetres, +Z up, origin at part centre.
"""
from build123d import Box, Cylinder, Pos, Rot, Align, Axis, fillet


def gen_step():
    _body = Cylinder(radius=7.5000, height=13.0000)
    _bore = Cylinder(radius=3.0000, height=14.3000)
    part = (_body - _bore)

    part.label = "cam_lock"
    return part
