"""Auto-generated CAD part 'cover_cap' (shape=cap) for usermanualXR.

Generated by spatail_cad_templates.py - edit the build-plan `cad` block or
supply a bespoke generator instead of hand-editing this file.
Units: millimetres, +Z up, origin at part centre.
"""
from build123d import Box, Cylinder, Pos, Rot, Align, Axis, fillet


def gen_step():
    part = Cylinder(radius=6.0000, height=4.5000)

    part.label = "cover_cap"
    return part
