"""Auto-generated CAD part 'dowel' (shape=dowel) for usermanualXR.

Generated by spatail_cad_templates.py - edit the build-plan `cad` block or
supply a bespoke generator instead of hand-editing this file.
Units: millimetres, +Z up, origin at part centre.
"""
from build123d import Box, Cylinder, Pos, Rot, Align, Axis, fillet


def gen_step():
    part = Rot(0, 90, 0) * Cylinder(radius=4.0000, height=35.0000)

    part.label = "dowel"
    return part
