"""Auto-generated CAD part 'screw' (shape=screw) for usermanualXR.

Generated by spatail_cad_templates.py - edit the build-plan `cad` block or
supply a bespoke generator instead of hand-editing this file.
Units: millimetres, +Z up, origin at part centre.
"""
from build123d import Box, Cylinder, Pos, Rot, Align, Axis, fillet


def gen_step():
    _shank = Cylinder(radius=3.0000, height=40.0000)
    _head = Pos(0, 0, 20.0000) * Cylinder(radius=5.7000, height=5.6000, align=(Align.CENTER, Align.CENTER, Align.MIN))
    part = Rot(0, 90, 0) * (_shank + _head)

    part.label = "screw"
    return part
