"""Auto-generated CAD part 'top' (shape=panel) for usermanualXR.

Generated by spatail_cad_templates.py - edit the build-plan `cad` block or
supply a bespoke generator instead of hand-editing this file.
Units: millimetres, +Z up, origin at part centre.
"""
from build123d import Box, Cylinder, Pos, Rot, Align, Axis, fillet


def gen_step():
    part = Box(344.0000, 390.0000, 38.0000)
    try:
        part = fillet(part.edges(), radius=2.0000)
    except Exception:
        pass

    part.label = "top"
    return part
