"""Auto-generated CAD part 'backrest_support' (shape=panel) for usermanualXR.

Generated by spatail_cad_templates.py - edit the build-plan `cad` block or
supply a bespoke generator instead of hand-editing this file.
Units: millimetres, +Z up, origin at part centre.
"""
from build123d import Box, Cylinder, Pos, Rot, Align, Axis, fillet


def gen_step():
    part = Box(400.0000, 40.0000, 350.0000)
    try:
        part = fillet(part.edges(), radius=2.0000)
    except Exception:
        pass

    part.label = "backrest_support"
    return part
