"""Auto-generated CAD part 'base_5_star' (shape=bar) for usermanualXR.

Generated by spatail_cad_templates.py - edit the build-plan `cad` block or
supply a bespoke generator instead of hand-editing this file.
Units: millimetres, +Z up, origin at part centre.
"""
from build123d import Box, Cylinder, Pos, Rot, Align, Axis, fillet


def gen_step():
    part = Box(600.0000, 600.0000, 30.0000)
    try:
        part = fillet(part.edges().filter_by(Axis.Y), radius=7.5000)
    except Exception:
        pass

    part.label = "base_5_star"
    return part
