"""Auto-generated CAD part 'gas_lift_cylinder' (shape=bar) for usermanualXR.

Generated by spatail_cad_templates.py - edit the build-plan `cad` block or
supply a bespoke generator instead of hand-editing this file.
Units: millimetres, +Z up, origin at part centre.
"""
from build123d import Box, Cylinder, Pos, Rot, Align, Axis, fillet


def gen_step():
    part = Box(50.0000, 50.0000, 350.0000)
    try:
        part = fillet(part.edges().filter_by(Axis.Z), radius=12.5000)
    except Exception:
        pass

    part.label = "gas_lift_cylinder"
    return part
