import Foundation

// Educational Wrapper — reading content + selection model + client prompt builder.
//
// The reader content (book + concept pages) is bundled as Resources/educational_reader.json
// (generated by studio/educational/build_cache.py from the demo reader). Decoded here so
// ReadingView can show real, selectable educational text offline. Platform-neutral data.

struct CapturedSelection: Codable, Equatable {
    var selectedText: String
    var surroundingContext: String = ""
    var sourceType: String = "book_page"
    var pageNumber: Int = 0
}

struct ReaderConcept: Decodable, Identifiable {
    let id: String
    var page: Int = 0
    let title: String
    var selectionTargets: [String] = []
    var learningGoal: String = ""
    var recommendedRepresentation: String = ""
    let body: String
    var experienceBeats: [String] = []
}

struct ReaderBookInfo: Decodable {
    let title: String
    var subtitle: String = ""
    var academicBasis: String = ""
}

private struct ReaderDoc: Decodable {
    let book: ReaderBookInfo
    let concepts: [ReaderConcept]
}

/// Loads the bundled reader once; falls back to a tiny embedded set if absent.
enum EducationalReader {
    static let book: ReaderBookInfo = loaded.book
    static let concepts: [ReaderConcept] = loaded.concepts

    private static let loaded: (book: ReaderBookInfo, concepts: [ReaderConcept]) = {
        if let url = Bundle.main.url(forResource: "educational_reader", withExtension: "json"),
           let data = try? Data(contentsOf: url),
           let doc = try? JSONDecoder().decode(ReaderDoc.self, from: data),
           !doc.concepts.isEmpty {
            return (doc.book, doc.concepts)
        }
        return (ReaderBookInfo(title: "SPATAIL Reader", subtitle: "Educational Wrapper"),
                [ReaderConcept(id: "cell_division", title: "Cell Division",
                               selectionTargets: ["cell division"],
                               learningGoal: "Explain how one parent cell becomes two daughter cells.",
                               recommendedRepresentation: "timeline",
                               body: "Cell division is the process by which one parent cell divides into two daughter cells.",
                               experienceBeats: [])])
    }()

    static func concept(matching text: String) -> ReaderConcept? {
        let s = text.lowercased().trimmingCharacters(in: .whitespacesAndNewlines)
        if let exact = concepts.first(where: { $0.selectionTargets.contains { $0.lowercased() == s } }) {
            return exact
        }
        return concepts.first { c in c.title.lowercased().contains(s) || s.contains(c.title.lowercased()) }
    }
}

/// Client-side mirror of studio/educational/prompt_builder.py — builds the "stronger"
/// prompt for display/edit. The server builds the authoritative one when the job runs.
enum EducationalPromptBuilder {
    static func build(for selection: CapturedSelection) -> String {
        let concept = EducationalReader.concept(matching: selection.selectedText)
        let rep = (concept?.recommendedRepresentation ?? "guided spatial explanation")
            .replacingOccurrences(of: "_", with: " ")
        let goal = concept?.learningGoal ?? "Explain \(selection.selectedText) clearly."
        var prompt = "Create an educational spatial explanation of \"\(selection.selectedText)\". "
        prompt += "Learning goal: \(goal) Prefer a \(rep) with labeled phases, progressive reveal, "
        prompt += "and interactive controls (step through, tap to highlight, isolate parts, reset)."
        return prompt
    }
}
